### ISSUE TITLE
Unable to create a docblock link for a `const` variable

### ISSUE THREAD

**Issue by Shrugsy** [phryneas/remark-typescript-tools#1]
While working on the [rtk-query](https://github.com/rtk-incubator/rtk-query) repo, I found that I was unable to create a docblock link for a `const` variable.

Reproduction steps:
- Add the following to `src/retry.ts`
```ts
/**
 * this is foo
 */
function foo() {}

/**
 * this is bar
 */
const bar = () => {}
```
- In a docusaurus markdown file (e.g. `docs/concepts/error-handling`), try create the following docblock link:
```md
[summary](docblock://retry.ts?token=foo)
```
- Observe that it works
- Replace it with the following docblock link:
```md
[summary](docblock://retry.ts?token=bar)
```
- Observe that docusaurus will fail to compile with an error like so:
```
../docs/concepts/error-handling.md
TypeError: Cannot read property 'textRange' of undefined
 @ ./.docusaurus/registry.js 1:5599-5665 1:5431-5552
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 ```

**Comment by phryneas** [comment]
remark-typescript-tools 1.0.4 published 🎉
 
 give it a spin :)

**Comment by Shrugsy** [comment]
Looks to be all good now, thanks!
